### ISSUE TITLE
Watch template, but don't compile as its own page

### ISSUE THREAD

**Issue by hhsnopek** [static-dev/spike-rooftop#28]
Right now you have to modify a different file to have your template recompile. It would be great to still be able to watch the template and trigger a recompile, without compiling the template as if it was its own page

**Comment by jescalan** [comment]
This is an issue with posthtml-jade: https://github.com/posthtml/posthtml-jade/issues/5 -- will be addressed there or just work once we swap over to sugarml stack.

**Comment by michaelcd** [comment]
Isn't this also related to the ignore options in spike's config? Because the template file begins with an underscore webpack will not trigger a new compilation when a file beginning with `_` is changed. 

```javascript
ignore: ['**/layout.jade', '**/_*', '**/.*', '**/data/*', 'readme.md'],
```

A temporary workaround: if you remove the underscore and and hardcode a temporary `item` variable in your template (so that it won't generate an error), you can edit your template and webpack will trigger a new build. This might save you some time so you don't have to constantly change a separate file. 

```jade
  -
    if (item === undefined) {
      const item = rooftop.posts[0]
    }
```

**Comment by jescalan** [comment]
It will as long as that file is a dependency of another file. The ignores are just for compiled files, not watched.

**Comment by hhsnopek** [comment]
In this case the template will always be ignored, unless we remove it from the ignores global?
